{{- if .Values.httproute.enabled -}}
{{- $fullName := include "zot.fullname" . -}}
{{- $httpPort := .Values.service.port -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    {{- with .Values.httproute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httproute.parentRefs }}
  parentRefs:
    {{- range . }}
    - group: {{ .group | default "gateway.networking.k8s.io" }}
      kind: {{ .kind | default "Gateway" }}
      name: {{ .name }}
      {{- with .namespace }}
      namespace: {{ . }}
      {{- end }}
      {{- with .sectionName }}
      sectionName: {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- with .Values.httproute.hostnames }}
  hostnames:
    {{- range . }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.httproute.rules }}
    {{- range .Values.httproute.rules }}
    - {{- with .matches }}
      matches:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      backendRefs:
        - group: ''
          kind: Service
          name: {{ $fullName }}
          port: {{ $httpPort }}
    {{- end }}
    {{- else }}
    - matches:
      - path:
          type: {{ .Values.httproute.pathType | default "PathPrefix" }}
          value: {{ .Values.httproute.path | default "/" }}
      backendRefs:
        - group: ''
          kind: Service
          name: {{ $fullName }}
          port: {{ $httpPort }}
    {{- end }}
{{- end }}
